var data = [
    {
        "id": 1,
        "name": "Mehmet Berber",
        "category": "Berber",
        "services": ["Saç", "Sakal", "Fön", "Maske", "Masaj", "Ense", "Ağda"],
        "city": "Adana",
        "district": "Seyhan",
        "working_hours": "8.00-16.00",
        "workers": [
            {
                "id": 1,
                "name": "Mehmet",
                "surname": "Ali",
                "phone": "0532 123 45 67",
                "email": "mehmetali@gmail.com",
                "services": ["Fön", "Maske", "Masaj"],
            },
            {
                "id": 2,
                "name": "Ahmet",
                "surname": "Yılmaz",
                "phone": "0532 123 45 67",
                "email": "ahmetyilmaz@gmail.com",
                "services": ["Saç", "Sakal", "Fön", "Ense"],
            },
            {
                "id": 3,
                "name": "Hasan",
                "surname": "Yıldırım",
                "phone": "0532 123 45 67",
                "email": "hasanyildirim@gmail.com",
                "services": ["Saç", "Fön", "Ense"],
            },
            {
                "id": 4,
                "name": "Veli",
                "surname": "Şahin",
                "phone": "0532 123 45 67",
                "email": "velisimsek@gmail.com",
                "services": ["Sakal", "Maske", "Masaj"],
            },
            {
                "id": 5,
                "name": "Süha Can",
                "surname": "Uluer",
                "phone": "0532 123 45 67",
                "email": "sculuer@gmail.com",
                "services": ["Sakal", "Maske", "Ağda"],
            },
        ]
    },
    {
        "id": 1,
        "name": "Ahmet Berber",
        "category": "Güzellik Salonu",
        "services": ["Saç", "Sakal", "Fön", "Maske", "Masaj", "Ense"],
        "city": "Adana",
        "district": "Seyhan",
        "working_hours": "8.00-16.00",
        "workers": [
            {
                "id": 1,
                "name": "Mehmet",
                "surname": "Ali",
                "phone": "0532 123 45 67",
                "email": "mehmetali@gmail.com",
                "services": ["Fön", "Maske", "Masaj"],
            },
            {
                "id": 2,
                "name": "Ahmet",
                "surname": "Yılmaz",
                "phone": "0532 123 45 67",
                "email": "ahmetyilmaz@gmail.com",
                "services": ["Saç", "Sakal", "Fön", "Ense"],
            },
            {
                "id": 3,
                "name": "Hasan",
                "surname": "Yıldırım",
                "phone": "0532 123 45 67",
                "email": "hasanyildirim@gmail.com",
                "services": ["Saç", "Fön", "Ense"],
            },
            {
                "id": 4,
                "name": "Veli",
                "surname": "Şahin",
                "phone": "0532 123 45 67",
                "email": "velisimsek@gmail.com",
                "services": ["Sakal", "Maske", "Masaj"],
            },
            {
                "id": 5,
                "name": "Süha Can",
                "surname": "Uluer",
                "phone": "0532 123 45 67",
                "email": "sculuer@gmail.com",
                "services": ["Sakal", "Maske", "Masaj"],
            },
        ]
    },
    {
        "id": 1,
        "name": "Hasan Berber",
        "category": "Kuaför",
        "services": ["Saç", "Sakal", "Fön", "Maske", "Masaj", "Ense"],
        "city": "Adana",
        "district": "Seyhan",
        "working_hours": "8.00-16.00",
        "workers": [
            {
                "id": 1,
                "name": "Mehmet",
                "surname": "Ali",
                "phone": "0532 123 45 67",
                "email": "mehmetali@gmail.com",
                "services": ["Fön", "Maske", "Masaj"],
            },
            {
                "id": 2,
                "name": "Ahmet",
                "surname": "Yılmaz",
                "phone": "0532 123 45 67",
                "email": "ahmetyilmaz@gmail.com",
                "services": ["Saç", "Sakal", "Fön", "Ense"],
            },
            {
                "id": 3,
                "name": "Hasan",
                "surname": "Yıldırım",
                "phone": "0532 123 45 67",
                "email": "hasanyildirim@gmail.com",
                "services": ["Saç", "Fön", "Ense"],
            },
            {
                "id": 4,
                "name": "Veli",
                "surname": "Şahin",
                "phone": "0532 123 45 67",
                "email": "velisimsek@gmail.com",
                "services": ["Sakal", "Maske", "Masaj"],
            },
            {
                "id": 5,
                "name": "Süha Can",
                "surname": "Uluer",
                "phone": "0532 123 45 67",
                "email": "sculuer@gmail.com",
                "services": ["Sakal", "Maske", "Masaj"],
            },
        ]
    },
    {
        "id": 1,
        "name": "Makkas Berber",
        "category": "Psikolog",
        "services": ["Saç", "Sakal", "Fön", "Maske", "Masaj", "Ense"],
        "city": "Adana",
        "district": "Seyhan",
        "working_hours": "8.00-16.00",
        "workers": [
            {
                "id": 1,
                "name": "Mehmet",
                "surname": "Ali",
                "phone": "0532 123 45 67",
                "email": "mehmetali@gmail.com",
                "services": ["Fön", "Maske", "Masaj"],
            },
            {
                "id": 2,
                "name": "Ahmet",
                "surname": "Yılmaz",
                "phone": "0532 123 45 67",
                "email": "ahmetyilmaz@gmail.com",
                "services": ["Saç", "Sakal", "Fön", "Ense"],
            },
            {
                "id": 3,
                "name": "Hasan",
                "surname": "Yıldırım",
                "phone": "0532 123 45 67",
                "email": "hasanyildirim@gmail.com",
                "services": ["Saç", "Fön", "Ense"],
            },
            {
                "id": 4,
                "name": "Veli",
                "surname": "Şahin",
                "phone": "0532 123 45 67",
                "email": "velisimsek@gmail.com",
                "services": ["Sakal", "Maske", "Masaj"],
            },
            {
                "id": 5,
                "name": "Süha Can",
                "surname": "Uluer",
                "phone": "0532 123 45 67",
                "email": "sculuer@gmail.com",
                "services": ["Sakal", "Maske", "Masaj"],
            },
        ]
    },
]

export default data;
